package com.revature.studyforce.user.repository;

import com.revature.studyforce.user.model.User;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import java.sql.Timestamp;
import java.util.Optional;

/**
 * Repository for Basic repository for {@link User}
 * @author Lok Kan Kung
 */
@RepositoryRestResource(collectionResourceRel = "Users", path = "user")
public interface UserRepository extends JpaRepository<User,Integer> {
    /*
     * Find by ID and find All generated by JPA API
     */


    /*
     * Find user using email
     */
    Optional<User> findByEmail(String email);

    /*
     * Find list of users with certain First Name or Last Name
     */
    Page<User> findByNameIgnoreCase(String firstName, Pageable pageable);

    /*
     * Find Users after registration time stamp
     */
    Page<User> findByRegistrationTimeAfter(Timestamp creation, Pageable pageable);
}